/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BloodType = { 'AB_Neg' : null } |
  { 'AB_Pos' : null } |
  { 'B_Neg' : null } |
  { 'B_Pos' : null } |
  { 'A_Neg' : null } |
  { 'A_Pos' : null } |
  { 'O_Neg' : null } |
  { 'O_Pos' : null };
export interface DonationCenter {
  'id' : bigint,
  'hours' : string,
  'city' : string,
  'name' : string,
  'donorType' : DonorType,
  'address' : string,
  'availableBloodTypes' : Array<BloodType>,
  'phone' : string,
}
export interface DonationRecord {
  'donationType' : DonorType,
  'center' : string,
  'status' : DonationStatus,
  'bloodType' : [] | [BloodType],
  'organ' : [] | [Organ],
  'donor' : Principal,
  'donationDate' : bigint,
}
export type DonationStatus = { 'scheduled' : null } |
  { 'completed' : null };
export interface DonorProfile {
  'bloodType' : BloodType,
  'organs' : Array<Organ>,
  'user' : Principal,
  'donorType' : DonorType,
  'medicalHistoryAcknowledged' : boolean,
  'registrationDate' : bigint,
}
export interface DonorPublicInfo {
  'center' : [] | [string],
  'bloodType' : BloodType,
  'lastDonationDate' : [] | [bigint],
  'donorType' : DonorType,
  'firstName' : string,
}
export type DonorType = { 'organ' : null } |
  { 'both' : null } |
  { 'blood' : null };
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type Organ = { 'pancreas' : null } |
  { 'heart' : null } |
  { 'corneas' : null } |
  { 'liver' : null } |
  { 'lungs' : null } |
  { 'kidney' : null } |
  { 'intestines' : null };
export interface Stats {
  'totalLivesSaved' : bigint,
  'totalBloodUnits' : bigint,
  'totalDonors' : bigint,
}
export interface UserProfile {
  'age' : bigint,
  'bloodType' : BloodType,
  'name' : string,
  'email' : string,
  'address' : string,
  'gender' : Gender,
  'emergencyContactPhone' : string,
  'emergencyContactName' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDonationCenter' : ActorMethod<[DonationCenter], bigint>,
  'addDonationRecord' : ActorMethod<[DonationRecord], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDonationCenters' : ActorMethod<
    [[] | [string], [] | [DonorType]],
    Array<DonationCenter>
  >,
  'getDonors' : ActorMethod<[], Array<DonorPublicInfo>>,
  'getMyProfile' : ActorMethod<[], [UserProfile, [] | [DonorProfile]]>,
  'getNextId' : ActorMethod<[], bigint>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerDonor' : ActorMethod<[DonorProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'updateDonationRecord' : ActorMethod<[bigint, DonationStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];