/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DonorType = IDL.Variant({
  'organ' : IDL.Null,
  'both' : IDL.Null,
  'blood' : IDL.Null,
});
export const BloodType = IDL.Variant({
  'AB_Neg' : IDL.Null,
  'AB_Pos' : IDL.Null,
  'B_Neg' : IDL.Null,
  'B_Pos' : IDL.Null,
  'A_Neg' : IDL.Null,
  'A_Pos' : IDL.Null,
  'O_Neg' : IDL.Null,
  'O_Pos' : IDL.Null,
});
export const DonationCenter = IDL.Record({
  'id' : IDL.Nat,
  'hours' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'donorType' : DonorType,
  'address' : IDL.Text,
  'availableBloodTypes' : IDL.Vec(BloodType),
  'phone' : IDL.Text,
});
export const DonationStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Organ = IDL.Variant({
  'pancreas' : IDL.Null,
  'heart' : IDL.Null,
  'corneas' : IDL.Null,
  'liver' : IDL.Null,
  'lungs' : IDL.Null,
  'kidney' : IDL.Null,
  'intestines' : IDL.Null,
});
export const DonationRecord = IDL.Record({
  'donationType' : DonorType,
  'center' : IDL.Text,
  'status' : DonationStatus,
  'bloodType' : IDL.Opt(BloodType),
  'organ' : IDL.Opt(Organ),
  'donor' : IDL.Principal,
  'donationDate' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'bloodType' : BloodType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'gender' : Gender,
  'emergencyContactPhone' : IDL.Text,
  'emergencyContactName' : IDL.Text,
  'phone' : IDL.Text,
});
export const DonorPublicInfo = IDL.Record({
  'center' : IDL.Opt(IDL.Text),
  'bloodType' : BloodType,
  'lastDonationDate' : IDL.Opt(IDL.Int),
  'donorType' : DonorType,
  'firstName' : IDL.Text,
});
export const DonorProfile = IDL.Record({
  'bloodType' : BloodType,
  'organs' : IDL.Vec(Organ),
  'user' : IDL.Principal,
  'donorType' : DonorType,
  'medicalHistoryAcknowledged' : IDL.Bool,
  'registrationDate' : IDL.Int,
});
export const Stats = IDL.Record({
  'totalLivesSaved' : IDL.Nat,
  'totalBloodUnits' : IDL.Nat,
  'totalDonors' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDonationCenter' : IDL.Func([DonationCenter], [IDL.Nat], []),
  'addDonationRecord' : IDL.Func([DonationRecord], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDonationCenters' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(DonorType)],
      [IDL.Vec(DonationCenter)],
      ['query'],
    ),
  'getDonors' : IDL.Func([], [IDL.Vec(DonorPublicInfo)], ['query']),
  'getMyProfile' : IDL.Func(
      [],
      [UserProfile, IDL.Opt(DonorProfile)],
      ['query'],
    ),
  'getNextId' : IDL.Func([], [IDL.Nat], []),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerDonor' : IDL.Func([DonorProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [], []),
  'updateDonationRecord' : IDL.Func([IDL.Nat, DonationStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DonorType = IDL.Variant({
    'organ' : IDL.Null,
    'both' : IDL.Null,
    'blood' : IDL.Null,
  });
  const BloodType = IDL.Variant({
    'AB_Neg' : IDL.Null,
    'AB_Pos' : IDL.Null,
    'B_Neg' : IDL.Null,
    'B_Pos' : IDL.Null,
    'A_Neg' : IDL.Null,
    'A_Pos' : IDL.Null,
    'O_Neg' : IDL.Null,
    'O_Pos' : IDL.Null,
  });
  const DonationCenter = IDL.Record({
    'id' : IDL.Nat,
    'hours' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'donorType' : DonorType,
    'address' : IDL.Text,
    'availableBloodTypes' : IDL.Vec(BloodType),
    'phone' : IDL.Text,
  });
  const DonationStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Organ = IDL.Variant({
    'pancreas' : IDL.Null,
    'heart' : IDL.Null,
    'corneas' : IDL.Null,
    'liver' : IDL.Null,
    'lungs' : IDL.Null,
    'kidney' : IDL.Null,
    'intestines' : IDL.Null,
  });
  const DonationRecord = IDL.Record({
    'donationType' : DonorType,
    'center' : IDL.Text,
    'status' : DonationStatus,
    'bloodType' : IDL.Opt(BloodType),
    'organ' : IDL.Opt(Organ),
    'donor' : IDL.Principal,
    'donationDate' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'bloodType' : BloodType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'gender' : Gender,
    'emergencyContactPhone' : IDL.Text,
    'emergencyContactName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DonorPublicInfo = IDL.Record({
    'center' : IDL.Opt(IDL.Text),
    'bloodType' : BloodType,
    'lastDonationDate' : IDL.Opt(IDL.Int),
    'donorType' : DonorType,
    'firstName' : IDL.Text,
  });
  const DonorProfile = IDL.Record({
    'bloodType' : BloodType,
    'organs' : IDL.Vec(Organ),
    'user' : IDL.Principal,
    'donorType' : DonorType,
    'medicalHistoryAcknowledged' : IDL.Bool,
    'registrationDate' : IDL.Int,
  });
  const Stats = IDL.Record({
    'totalLivesSaved' : IDL.Nat,
    'totalBloodUnits' : IDL.Nat,
    'totalDonors' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDonationCenter' : IDL.Func([DonationCenter], [IDL.Nat], []),
    'addDonationRecord' : IDL.Func([DonationRecord], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDonationCenters' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(DonorType)],
        [IDL.Vec(DonationCenter)],
        ['query'],
      ),
    'getDonors' : IDL.Func([], [IDL.Vec(DonorPublicInfo)], ['query']),
    'getMyProfile' : IDL.Func(
        [],
        [UserProfile, IDL.Opt(DonorProfile)],
        ['query'],
      ),
    'getNextId' : IDL.Func([], [IDL.Nat], []),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerDonor' : IDL.Func([DonorProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [], []),
    'updateDonationRecord' : IDL.Func([IDL.Nat, DonationStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };