/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DonationCenter {
    id: bigint;
    hours: string;
    city: string;
    name: string;
    donorType: DonorType;
    address: string;
    availableBloodTypes: Array<BloodType>;
    phone: string;
}
export interface DonationRecord {
    donationType: DonorType;
    center: string;
    status: DonationStatus;
    bloodType?: BloodType;
    organ?: Organ;
    donor: Principal;
    donationDate: bigint;
}
export interface Stats {
    totalLivesSaved: bigint;
    totalBloodUnits: bigint;
    totalDonors: bigint;
}
export interface DonorProfile {
    bloodType: BloodType;
    organs: Array<Organ>;
    user: Principal;
    donorType: DonorType;
    medicalHistoryAcknowledged: boolean;
    registrationDate: bigint;
}
export interface UserProfile {
    age: bigint;
    bloodType: BloodType;
    name: string;
    email: string;
    address: string;
    gender: Gender;
    emergencyContactPhone: string;
    emergencyContactName: string;
    phone: string;
}
export interface DonorPublicInfo {
    center?: string;
    bloodType: BloodType;
    lastDonationDate?: bigint;
    donorType: DonorType;
    firstName: string;
}
export enum BloodType {
    AB_Neg = "AB_Neg",
    AB_Pos = "AB_Pos",
    B_Neg = "B_Neg",
    B_Pos = "B_Pos",
    A_Neg = "A_Neg",
    A_Pos = "A_Pos",
    O_Neg = "O_Neg",
    O_Pos = "O_Pos"
}
export enum DonationStatus {
    scheduled = "scheduled",
    completed = "completed"
}
export enum DonorType {
    organ = "organ",
    both = "both",
    blood = "blood"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum Organ {
    pancreas = "pancreas",
    heart = "heart",
    corneas = "corneas",
    liver = "liver",
    lungs = "lungs",
    kidney = "kidney",
    intestines = "intestines"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDonationCenter(center: DonationCenter): Promise<bigint>;
    addDonationRecord(record: DonationRecord): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDonationCenters(city: string | null, donorType: DonorType | null): Promise<Array<DonationCenter>>;
    getDonors(): Promise<Array<DonorPublicInfo>>;
    getMyProfile(): Promise<[UserProfile, DonorProfile | null]>;
    getNextId(): Promise<bigint>;
    getStats(): Promise<Stats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerDonor(donorProfile: DonorProfile): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedData(): Promise<void>;
    updateDonationRecord(id: bigint, status: DonationStatus): Promise<void>;
}
import type { BloodType as _BloodType, DonationCenter as _DonationCenter, DonationRecord as _DonationRecord, DonationStatus as _DonationStatus, DonorProfile as _DonorProfile, DonorPublicInfo as _DonorPublicInfo, DonorType as _DonorType, Gender as _Gender, Organ as _Organ, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDonationCenter(arg0: DonationCenter): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDonationCenter(to_candid_DonationCenter_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDonationCenter(to_candid_DonationCenter_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addDonationRecord(arg0: DonationRecord): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDonationRecord(to_candid_DonationRecord_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDonationRecord(to_candid_DonationRecord_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonationCenters(arg0: string | null, arg1: DonorType | null): Promise<Array<DonationCenter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationCenters(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationCenters(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonors(): Promise<Array<DonorPublicInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonors();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonors();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<[UserProfile, DonorProfile | null]> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return [
                    from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result[0]),
                    from_candid_opt_n38(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return [
                from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result[0]),
                from_candid_opt_n38(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
    async getNextId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextId();
            return result;
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerDonor(arg0: DonorProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDonor(to_candid_DonorProfile_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDonor(to_candid_DonorProfile_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async updateDonationRecord(arg0: bigint, arg1: DonationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonationRecord(arg0, to_candid_DonationStatus_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonationRecord(arg0, to_candid_DonationStatus_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BloodType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodType): BloodType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_DonationCenter_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonationCenter): DonationCenter {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_DonorProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonorProfile): DonorProfile {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_DonorPublicInfo_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonorPublicInfo): DonorPublicInfo {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_DonorType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonorType): DonorType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Organ_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Organ): Organ {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DonorProfile]): DonorProfile | null {
    return value.length === 0 ? null : from_candid_DonorProfile_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bloodType: _BloodType;
    name: string;
    email: string;
    address: string;
    gender: _Gender;
    emergencyContactPhone: string;
    emergencyContactName: string;
    phone: string;
}): {
    age: bigint;
    bloodType: BloodType;
    name: string;
    email: string;
    address: string;
    gender: Gender;
    emergencyContactPhone: string;
    emergencyContactName: string;
    phone: string;
} {
    return {
        age: value.age,
        bloodType: from_candid_BloodType_n19(_uploadFile, _downloadFile, value.bloodType),
        name: value.name,
        email: value.email,
        address: value.address,
        gender: from_candid_Gender_n21(_uploadFile, _downloadFile, value.gender),
        emergencyContactPhone: value.emergencyContactPhone,
        emergencyContactName: value.emergencyContactName,
        phone: value.phone
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    hours: string;
    city: string;
    name: string;
    donorType: _DonorType;
    address: string;
    availableBloodTypes: Array<_BloodType>;
    phone: string;
}): {
    id: bigint;
    hours: string;
    city: string;
    name: string;
    donorType: DonorType;
    address: string;
    availableBloodTypes: Array<BloodType>;
    phone: string;
} {
    return {
        id: value.id,
        hours: value.hours,
        city: value.city,
        name: value.name,
        donorType: from_candid_DonorType_n30(_uploadFile, _downloadFile, value.donorType),
        address: value.address,
        availableBloodTypes: from_candid_vec_n32(_uploadFile, _downloadFile, value.availableBloodTypes),
        phone: value.phone
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    center: [] | [string];
    bloodType: _BloodType;
    lastDonationDate: [] | [bigint];
    donorType: _DonorType;
    firstName: string;
}): {
    center?: string;
    bloodType: BloodType;
    lastDonationDate?: bigint;
    donorType: DonorType;
    firstName: string;
} {
    return {
        center: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.center)),
        bloodType: from_candid_BloodType_n19(_uploadFile, _downloadFile, value.bloodType),
        lastDonationDate: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.lastDonationDate)),
        donorType: from_candid_DonorType_n30(_uploadFile, _downloadFile, value.donorType),
        firstName: value.firstName
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bloodType: _BloodType;
    organs: Array<_Organ>;
    user: Principal;
    donorType: _DonorType;
    medicalHistoryAcknowledged: boolean;
    registrationDate: bigint;
}): {
    bloodType: BloodType;
    organs: Array<Organ>;
    user: Principal;
    donorType: DonorType;
    medicalHistoryAcknowledged: boolean;
    registrationDate: bigint;
} {
    return {
        bloodType: from_candid_BloodType_n19(_uploadFile, _downloadFile, value.bloodType),
        organs: from_candid_vec_n41(_uploadFile, _downloadFile, value.organs),
        user: value.user,
        donorType: from_candid_DonorType_n30(_uploadFile, _downloadFile, value.donorType),
        medicalHistoryAcknowledged: value.medicalHistoryAcknowledged,
        registrationDate: value.registrationDate
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AB_Neg: null;
} | {
    AB_Pos: null;
} | {
    B_Neg: null;
} | {
    B_Pos: null;
} | {
    A_Neg: null;
} | {
    A_Pos: null;
} | {
    O_Neg: null;
} | {
    O_Pos: null;
}): BloodType {
    return "AB_Neg" in value ? BloodType.AB_Neg : "AB_Pos" in value ? BloodType.AB_Pos : "B_Neg" in value ? BloodType.B_Neg : "B_Pos" in value ? BloodType.B_Pos : "A_Neg" in value ? BloodType.A_Neg : "A_Pos" in value ? BloodType.A_Pos : "O_Neg" in value ? BloodType.O_Neg : "O_Pos" in value ? BloodType.O_Pos : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organ: null;
} | {
    both: null;
} | {
    blood: null;
}): DonorType {
    return "organ" in value ? DonorType.organ : "both" in value ? DonorType.both : "blood" in value ? DonorType.blood : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pancreas: null;
} | {
    heart: null;
} | {
    corneas: null;
} | {
    liver: null;
} | {
    lungs: null;
} | {
    kidney: null;
} | {
    intestines: null;
}): Organ {
    return "pancreas" in value ? Organ.pancreas : "heart" in value ? Organ.heart : "corneas" in value ? Organ.corneas : "liver" in value ? Organ.liver : "lungs" in value ? Organ.lungs : "kidney" in value ? Organ.kidney : "intestines" in value ? Organ.intestines : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DonationCenter>): Array<DonationCenter> {
    return value.map((x)=>from_candid_DonationCenter_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BloodType>): Array<BloodType> {
    return value.map((x)=>from_candid_BloodType_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DonorPublicInfo>): Array<DonorPublicInfo> {
    return value.map((x)=>from_candid_DonorPublicInfo_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Organ>): Array<Organ> {
    return value.map((x)=>from_candid_Organ_n42(_uploadFile, _downloadFile, x));
}
function to_candid_BloodType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodType): _BloodType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_DonationCenter_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonationCenter): _DonationCenter {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_DonationRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonationRecord): _DonationRecord {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_DonationStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonationStatus): _DonationStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_DonorProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonorProfile): _DonorProfile {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_DonorType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonorType): _DonorType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_Organ_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Organ): _Organ {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonorType | null): [] | [_DonorType] {
    return value === null ? candid_none() : candid_some(to_candid_DonorType_n3(_uploadFile, _downloadFile, value));
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    hours: string;
    city: string;
    name: string;
    donorType: DonorType;
    address: string;
    availableBloodTypes: Array<BloodType>;
    phone: string;
}): {
    id: bigint;
    hours: string;
    city: string;
    name: string;
    donorType: _DonorType;
    address: string;
    availableBloodTypes: Array<_BloodType>;
    phone: string;
} {
    return {
        id: value.id,
        hours: value.hours,
        city: value.city,
        name: value.name,
        donorType: to_candid_DonorType_n3(_uploadFile, _downloadFile, value.donorType),
        address: value.address,
        availableBloodTypes: to_candid_vec_n5(_uploadFile, _downloadFile, value.availableBloodTypes),
        phone: value.phone
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bloodType: BloodType;
    organs: Array<Organ>;
    user: Principal;
    donorType: DonorType;
    medicalHistoryAcknowledged: boolean;
    registrationDate: bigint;
}): {
    bloodType: _BloodType;
    organs: Array<_Organ>;
    user: Principal;
    donorType: _DonorType;
    medicalHistoryAcknowledged: boolean;
    registrationDate: bigint;
} {
    return {
        bloodType: to_candid_BloodType_n6(_uploadFile, _downloadFile, value.bloodType),
        organs: to_candid_vec_n46(_uploadFile, _downloadFile, value.organs),
        user: value.user,
        donorType: to_candid_DonorType_n3(_uploadFile, _downloadFile, value.donorType),
        medicalHistoryAcknowledged: value.medicalHistoryAcknowledged,
        registrationDate: value.registrationDate
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bloodType: BloodType;
    name: string;
    email: string;
    address: string;
    gender: Gender;
    emergencyContactPhone: string;
    emergencyContactName: string;
    phone: string;
}): {
    age: bigint;
    bloodType: _BloodType;
    name: string;
    email: string;
    address: string;
    gender: _Gender;
    emergencyContactPhone: string;
    emergencyContactName: string;
    phone: string;
} {
    return {
        age: value.age,
        bloodType: to_candid_BloodType_n6(_uploadFile, _downloadFile, value.bloodType),
        name: value.name,
        email: value.email,
        address: value.address,
        gender: to_candid_Gender_n49(_uploadFile, _downloadFile, value.gender),
        emergencyContactPhone: value.emergencyContactPhone,
        emergencyContactName: value.emergencyContactName,
        phone: value.phone
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    donationType: DonorType;
    center: string;
    status: DonationStatus;
    bloodType?: BloodType;
    organ?: Organ;
    donor: Principal;
    donationDate: bigint;
}): {
    donationType: _DonorType;
    center: string;
    status: _DonationStatus;
    bloodType: [] | [_BloodType];
    organ: [] | [_Organ];
    donor: Principal;
    donationDate: bigint;
} {
    return {
        donationType: to_candid_DonorType_n3(_uploadFile, _downloadFile, value.donationType),
        center: value.center,
        status: to_candid_DonationStatus_n10(_uploadFile, _downloadFile, value.status),
        bloodType: value.bloodType ? candid_some(to_candid_BloodType_n6(_uploadFile, _downloadFile, value.bloodType)) : candid_none(),
        organ: value.organ ? candid_some(to_candid_Organ_n12(_uploadFile, _downloadFile, value.organ)) : candid_none(),
        donor: value.donor,
        donationDate: value.donationDate
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonationStatus): {
    scheduled: null;
} | {
    completed: null;
} {
    return value == DonationStatus.scheduled ? {
        scheduled: null
    } : value == DonationStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Organ): {
    pancreas: null;
} | {
    heart: null;
} | {
    corneas: null;
} | {
    liver: null;
} | {
    lungs: null;
} | {
    kidney: null;
} | {
    intestines: null;
} {
    return value == Organ.pancreas ? {
        pancreas: null
    } : value == Organ.heart ? {
        heart: null
    } : value == Organ.corneas ? {
        corneas: null
    } : value == Organ.liver ? {
        liver: null
    } : value == Organ.lungs ? {
        lungs: null
    } : value == Organ.kidney ? {
        kidney: null
    } : value == Organ.intestines ? {
        intestines: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonorType): {
    organ: null;
} | {
    both: null;
} | {
    blood: null;
} {
    return value == DonorType.organ ? {
        organ: null
    } : value == DonorType.both ? {
        both: null
    } : value == DonorType.blood ? {
        blood: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodType): {
    AB_Neg: null;
} | {
    AB_Pos: null;
} | {
    B_Neg: null;
} | {
    B_Pos: null;
} | {
    A_Neg: null;
} | {
    A_Pos: null;
} | {
    O_Neg: null;
} | {
    O_Pos: null;
} {
    return value == BloodType.AB_Neg ? {
        AB_Neg: null
    } : value == BloodType.AB_Pos ? {
        AB_Pos: null
    } : value == BloodType.B_Neg ? {
        B_Neg: null
    } : value == BloodType.B_Pos ? {
        B_Pos: null
    } : value == BloodType.A_Neg ? {
        A_Neg: null
    } : value == BloodType.A_Pos ? {
        A_Pos: null
    } : value == BloodType.O_Neg ? {
        O_Neg: null
    } : value == BloodType.O_Pos ? {
        O_Pos: null
    } : value;
}
function to_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Organ>): Array<_Organ> {
    return value.map((x)=>to_candid_Organ_n12(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BloodType>): Array<_BloodType> {
    return value.map((x)=>to_candid_BloodType_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
